name=Simple Ping Payload
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the simple example Ping Payload library for HSSSI-26 SlimSats
paragraph=This library provides an example simple Ping Payload capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=simple_ping_payload.h,simple_ping_payload.cpp