name=SlimSat Bus Database
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the Bus Database (DB) library for HSSSI-26 SlimSats
paragraph=This library provides the Bus Database capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=bus_db.h,bus_db.cpp