name=SlimSat Bus Time
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the S/C Bus Time library for HSSSI-26 SlimSats
paragraph=This library provides S/C Bus Time capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=sc_bus_time.h,sc_bus_time.cpp