name=SlimSat Bus Power Monitor
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the Bus Power Monitor for HSSSI-26 SlimSats
paragraph=This library provides the core Bus Power Monitor capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=bus_power_monitor.h,bus_power_monitor.cpp