name=SlimSat Bus Simple Timer
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the Bus Simple Timer library for HSSSI-26 SlimSats
paragraph=This library provides the core Bus Simple Timer capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=simple_timer.h,simple_timer.cpp