name=Message Circular Buffer
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the Message Circular Buffer library for HSSSI-26 SlimSats
paragraph=This library provides the core Message Circular Buffer capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=hhttps://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=msg_circular_buffer.h,msg_circular_buffer.cpp