/**
 * @file payload.cpp
 * @brief SlimSat Payload System Implementation
 * 
 * @details This file implements the Payload class methods for managing
 * the payload subsystem including sensor operations, measurement collection,
 * data processing, and command handling for SlimSat payload instruments.
 * 
 * CAPE-Twiggs HSSSI-26 SlimSat Project
 * Copyright (c) 2025, Eric Tapio. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for full license information.
 */

#include <payload.h>

/**
 * @brief Default constructor for the payload class
 * @details Initializes the payload system by setting up data members
 * and performing system initialization. This is the only constructor
 * available for the payload class.
 */
Payload::Payload(void) {
	// The default constructor, and only constructor, for the payload class
	initializeDataMembers();

	return;
}


/**
 * @brief Initialize payload data members
 * @details Sets all class data members to their default/initial values
 * including payload state, measurement arrays, and configuration parameters.
 */
void Payload::initializeDataMembers(void) {
	// This method initiailizes all class data members 

	num_measurements_to_take = 10;
	input_is_valid = 0;

	initializePayloadMessageBuffer();

	return;
}


/**
 * @brief Print payload information
 * @details Outputs comprehensive payload state information including
 * operational state, measurement configuration, and statistical data
 * for debugging and diagnostic purposes.
 */
void Payload::print(void) const {
	// This method prints the Payload data members

	Serial.println(F("\n ~ Printing Payload ..."));
	Serial.print(F("    Number Measurements is: "));
	Serial.println(num_measurements_to_take);
	Serial.print(F("    Input is Valid is: "));
	Serial.println(input_is_valid);
	Serial.println(F(""));
	 
	return;
}


/**
 * @brief Initialize payload system
 * @details Performs complete payload initialization including hardware
 * configuration, pin setup, and system state initialization. Sets
 * payload to STOPPED state for safe startup.
 */
void Payload::initializePayload(void) {
	// This method initializes the payload, which can include setting hardware pin directions and input/output states
	initializeDataMembers();
	return;
}


/**
 * Note: A Payload Message Buffer is provided, which may be used 
 * @brief Initialize payload message buffer
 * @details Clears the payload output message buffer by setting all
 * elements to null characters for clean message formatting.
 */
void Payload::initializePayloadMessageBuffer(void) {
	// This method initializes the payload message buffer used to output Payload data to the Bus
	memset(pl_output_msg_buffer, 0, sizeof(pl_output_msg_buffer));
	return;
}


void Payload::setNumMeasurementsToTake(uint8_t num_meas) {
	// This method sets the number of measurements data member
	
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F("\n ~ Setting Number of Measurements ..."));
	}

	// ALWAYS Validate the input before making setting changes
	// and use guards against invalid inputs
	if (num_meas <= PAYLOAD_DATA_ARY_SIZE) {
		num_measurements_to_take = num_meas;
	}
	else {
		Serial.print(F("\n ~ Ignoring invalid received number of measurements value of: "));
		Serial.println(num_meas);
	}
}


/**
 * @brief Handle payload command
 * @details Processes payload commands received from the bus.
 * Validates command IDs, executes appropriate actions, and generates
 * response messages. Returns the number of messages created for transmission.
 * This method can be customized by the payload development team as needed.
 * @param cmd_id Command identifier (30-39 range)
 * @param cmd_val Command value/parameter
 * @return Number of response messages generated
 */
//char* Payload::handlePayloadCommand(uint8_t cmd_id, uint32_t cmd_val, PlDataRec& pl_data_rec) {
char* Payload::handlePayloadCommand(uint8_t cmd_id, int32_t cmd_val, PlDataRec& pl_data_rec) {
	// This method handles payload commands received from the Bus
	// This method is to be populated, as desired, and tested by the payload development team
	// This method returns the number of payload messages generated by handling the given command. It is not required that this method do so. It may be modified, as needed
	
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.print(F("\n ~ Payload Handling Command with given Cmd ID: "));
		Serial.println(cmd_id);
	}

	if ((MIN_PL_CMD_ID <= cmd_id) && (cmd_id <= MAX_PL_CMD_ID)) {

		initializePayloadMessageBuffer();

		switch (cmd_id) {
		case (PING_PAYLOAD_CMD_ID):
			Serial.println(F("\n ~ Received Payload Ping command"));
			snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d", cmd_id);
			break;
		case (GET_NUMBER_MEASUREMENTS_TO_TAKE_CMD_ID):
			Serial.println(F("\n ~ Received command to get the number of range measurements to take"));
			snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d,%d", cmd_id, num_measurements_to_take);	
			break;
		case (SET_NUMBER_MEASUREMENTS_TO_TAKE_CMD_ID):
			Serial.println(F("\n ~ Received command to set the number of range measurements to take"));

			// ALWAYS validate inputs before using them
			if ((MIN_NUMBER_MEASUREMENTS <= cmd_val) && (cmd_val <= MAX_NUMBER_MEASUREMENTS)) {
				// Then set the number of measurements
				setNumMeasurementsToTake(cmd_val);
				snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d,%d", cmd_id, num_measurements_to_take);
			}
			else {
				snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "N,%d,%d", cmd_id, cmd_val);
			}
			break;
		case (TAKE_MEASUREMENTS_CMD_ID):
			Serial.println(F("\n ~ Received command to take a round of range measurements"));
			performPayloadOperationIteration(pl_data_rec);
			snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d", cmd_id);
			break;
		case (PRINT_MEASUREMENTS_CMD_ID):
			Serial.println(F("\n ~ Received command to print (but not return) the round of taken measurements"));
			pl_data_rec.printArray();
			snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d", cmd_id);
			break;

		case (MIN_PL_CMD_ID + 8):
		case (MIN_PL_CMD_ID + 9):
			Serial.println(F("\n ~ Note: Received Payload command that is not yet defined or supported"));
			
			snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "A,%d", cmd_id);
			break;
		}

		return pl_output_msg_buffer;
	}
	else {
		Serial.print(F("\n ~ Error: Encountered Invalid Payload Command ID: "));
		Serial.print(cmd_id);
		Serial.println(F(" . Ignoring!"));
		
		snprintf(pl_output_msg_buffer, sizeof(pl_output_msg_buffer), "N,%d", cmd_id);
	}
	
	// Return the number of output messages
	return pl_output_msg_buffer;
}


/**
 * @brief Find maximum range measurement
 * @details Searches through the range measurement array to find the largest
 * value and updates the max_measurement_value data member. Provides
 * optional verbose output for debugging.
 */
double Payload::getMaxRangeMeasurement(PlDataRec& pl_data_rec) {
	// This method deterermines the maximum value found in the range measurement array and updates the max measurement data member
	
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F("\n ~ Finding the Max Range Measurement ..."));
	}

	double max_measurement_value = pl_data_rec.getArrayElement(0);

	// Step through the array and find the largest value
	for (uint8_t i=0; i<num_measurements_to_take; i++) {
		if (pl_data_rec.getArrayElement(i) > max_measurement_value) {
			max_measurement_value = pl_data_rec.getArrayElement(i);
		}
	}

	// Assign the largest value to the data member
	//max_measurement_value = max_value;

	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.print(F("\n ~ Max Range Measurement is: "));
		Serial.println(max_measurement_value);
		Serial.println(F(""));
	}

	return max_measurement_value;
}


/**
 * @brief Find minimum range measurement
 * @details Searches through the range measurement array to find the smallest
 * value and updates the min_measurement_value data member. Provides
 * optional verbose output for debugging.
 */
double Payload::getMinRangeMeasurement(PlDataRec& pl_data_rec) {
	// This method deterermines the minimum value found in the range measurement array and updates the min measurement data member
	
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F(" ~ Finding the Min Range Measurement ..."));
	}
	
	double min_measurement_value = pl_data_rec.getArrayElement(0);

	// Step through the array and find the smallest value
	for (uint8_t i=0; i<num_measurements_to_take; i++) {
		if (pl_data_rec.getArrayElement(i) < min_measurement_value) {
			min_measurement_value = pl_data_rec.getArrayElement(i);
		}
	}

	// Assign the smallest value to the data member
	//min_measurement_value = min_value;

	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.print(F("\n ~ Min Range Measurement is: "));
		Serial.println(min_measurement_value);
		Serial.println(F(""));
	}

	return min_measurement_value;
}


/**
 * @brief Find mean range measurement
 * @details Calculates the arithmetic mean of all range measurements and
 * updates the mean_measurement_value data member. Handles both single
 * and multiple measurement cases.
 */
double Payload::getMeanRangeMeasurement(PlDataRec& pl_data_rec) {
	// This method deterermines the mean value of the range measurement array and updates the mean measurement data member

	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F("\n ~ Finding the Mean Range Measurement ..."));
	}
	
	double sum = 0;

	if (num_measurements_to_take == 1) {
		sum = pl_data_rec.getArrayElement(0);
	}
	else {
		// Step through the array and find the smallest value
		for (uint8_t i=0; i<num_measurements_to_take; i++) {
			sum += pl_data_rec.getArrayElement(i);
		}
	}

	// Compute the mean
	double mean_measurement_value = sum / num_measurements_to_take;

	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.print(F("\n ~ Mean Range Measurement is: "));
		Serial.println(mean_measurement_value);
		Serial.println(F(""));
	}

	return mean_measurement_value;
}


/**
 * @brief Get payload data string
 * @details Returns a pointer to the payload output message buffer
 * containing formatted payload data for transmission.
 * @return Pointer to payload data string buffer
 */
char* Payload::getPayloadDataStr(void) {
	// This method returns the Payload data string
	return pl_output_msg_buffer;
}


void Payload::performRoundofSensorMeasurements(PlDataRec& pl_data) {
	// This method performs a round of range measurements
	
	double measurement = 0.0;
	
	// Initialize the payload data array 
	pl_data.initializeArray();
	
	// Note pl_data.time & pl_data.pl_rec_num will both be populated by the bus before writing the data to flash memory (or outputting the data)
	// As a result, these two fields are not to be populated in the payload code file

	
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F(" ~ Performing Round of Range Measurements ..."));
		Serial.print(F("    num_measurements_to_take is: "));
		Serial.println(num_measurements_to_take);
	}

	for (uint8_t i=0; i<num_measurements_to_take; i++) {
		// An idea, if it is not already there. Add a commandable delta t between measurements
		measurement = (double)(Ping.getRangeMeasurementInCm());
		pl_data.setArrayElement(i, measurement);
	}

	// Then process the measurements
	pl_data.setArrayElement(MIN_MEASUREMENT_ARY_INDEX, getMinRangeMeasurement(pl_data));
	pl_data.setArrayElement(MAX_MEASUREMENT_ARY_INDEX, getMaxRangeMeasurement(pl_data));
	pl_data.setArrayElement(MEAN_MEASUREMENT_ARY_INDEX, getMeanRangeMeasurement(pl_data));
	pl_data.setArrayElement(SENSOR_2_MEASUREMENT_ARY_INDEX, getSensor2Measurement());

	return;
}


void Payload::performPayloadOperationIteration(PlDataRec& pl_data) {
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F("\n ~ Performing Payload Operation Iteration ..."));
	}
	
	performRoundofSensorMeasurements(pl_data);

	return;
}


double Payload::getSensor2Measurement(void) const {
	if (VERBOSE_PAYLOAD_OUTPUT) {
		Serial.println(F("\n ~ Getting Sensor 2 Measurement Value ..."));
	}
	
	return 23.45;
}