name=SlimSat SC Bus
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the S/C Bus library for HSSSI-26 SlimSats
paragraph=This library provides the core S/C Bus capability for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=slimsat_bus.h,slimsat_bus.cpp