name=SlimSat Payload Data Class
version=1.0
author=Eric Tapio eric.d.tapio@gmail.com
maintainer=Eric Tapio eric.d.tapio@gmail.com
sentence=This is the Payload Data Class for HSSSI-26 SlimSats
paragraph=This library provides the core Payload Data Class for the HSSSI-26 SlimSats
category=Device Control
url=https://github.com/eric-tapio/HSSSI26_SlimSat
architectures=
repository=https://github.com/eric-tapio/HSSSI26_SlimSat
license=MIT
includes=payload_data.h,payload_data.cpp