/**
 * @file slimsat_cmd_constants.h
 * @brief SlimSat Command Constants Header
 * 
 * @details This header file defines all command constants used in the SlimSat
 * NMEA message handling system. It includes command IDs for bus operations,
 * radio configuration, payload control, timing operations, and system
 * management functions. These constants ensure consistent command identification
 * across the entire SlimSat communication system.
 * 
 * CAPE-Twiggs HSSSI-26 SlimSat Project
 * Copyright (c) 2025, Eric Tapio. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root for full license information.
 */

#ifndef SLIMSAT_CMD_CONSTANTS_HEADER
#define SLIMSAT_CMD_CONSTANTS_HEADER

#define MIN_SLIMSAT_CMD_ID 1
#define MAX_SLIMSAT_CMD_ID 59

// Defined SlimSat Bus command values
#define PING_BUS_COMMAND_ID 1
#define GET_BUS_DB_REGISTER_VALUES_COMMAND_ID 2
#define GET_BUS_DATA_COMMAND_ID 3
#define GET_PAYLOAD_DATA_COMMAND_ID 4

#define GET_RADIO_FREQUENCY_COMMAND_ID 5
#define SET_RADIO_FREQUENCY_COMMAND_ID 6
#define GET_RADIO_BANDWIDTH_COMMAND_ID 7
#define SET_RADIO_BANDWIDTH_COMMAND_ID 8
#define GET_RADIO_SPREAD_FACTOR_COMMAND_ID 9
#define SET_RADIO_SPREAD_FACTOR_COMMAND_ID 10

#define GET_RADIO_CODING_RATE_COMMAND_ID 11
#define SET_RADIO_CODING_RATE_COMMAND_ID 12
#define GET_RADIO_OUTPUT_POWER_COMMAND_ID 13
#define SET_RADIO_OUTPUT_POWER_COMMAND_ID 14
#define GET_RADIO_CURRENT_LIMIT_COMMAND_ID 15
#define SET_RADIO_CURRENT_LIMIT_COMMAND_ID 16
#define GET_RADIO_PREAMBLE_LENGTH_COMMAND_ID 17
#define SET_RADIO_PREAMBLE_LENGTH_COMMAND_ID 18
#define GET_RADIO_GAIN_COMMAND_ID 19
#define SET_RADIO_GAIN_COMMAND_ID 20
#define GET_RADIO_FREQUENCY_ERROR_COMMAND_ID 21
#define GET_RADIO_SNR_COMMAND_ID 22

#define GET_RADIO_RSSI_COMMAND_ID 23
#define GET_BEACON_PERIOD_COMMAND_ID 24
#define SET_BEACON_PERIOD_COMMAND_ID 25
#define GET_BUS_MODE_COMMAND_ID 26
#define SET_BUS_MODE_COMMAND_ID 27
#define GET_BUS_EPOCH_TIME_COMMAND_ID 28
#define SET_BUS_EPOCH_TIME_COMMAND_ID 29
#define GET_BUS_TIME_COMMAND_ID 30
#define GET_BUS_SAFE_MODE_VOLTAGE_COMMAND_ID 31
#define SET_BUS_SAFE_MODE_VOLTAGE_COMMAND_ID 32
#define GET_BUS_DATA_RECORD_PERIOD_COMMAND_ID 33
#define SET_BUS_DATA_RECORD_PERIOD_COMMAND_ID 34
#define GET_PAYLOAD_OP_PERIOD_COMMAND_ID 35
#define SET_PAYLOAD_OP_PERIOD_COMMAND_ID 36
#define REBOOT_COMMAND_ID 37
#define GET_FLASH_REGISTER_VALUE_COMMAND_ID 38
#define SET_FLASH_REGISTER_VALUE_COMMAND_ID 39
#define ERASE_FLASH_CHIP_MEMORY_COMMAND_ID 40
#define ERASE_FLASH_BLOCK_MEMORY_COMMAND_ID 41
#define ERASE_FLASH_SECTOR_MEMORY_COMMAND_ID 42
#define ERASE_BUS_DATA_FLASH_BLOCKS_COMMAND_ID 43
#define ERASE_PAYLOAD_DATA_FLASH_BLOCKS_COMMAND_ID 44

#define GET_GPS_POSITION_COMMAND_ID 45
#define CUTDOWN_BURN_WIRE_COMMAND_ID 46
#define SLIMSAT_CMD_47 47
#define SLIMSAT_CMD_48 48
#define SLIMSAT_CMD_49 49

// Alloacated payload command values
// #define PAYLOAD_CMD_1 50
// #define PAYLOAD_CMD_2 51
// #define PAYLOAD_CMD_3 52
// #define PAYLOAD_CMD_4 53
// #define PAYLOAD_CMD_5 54
// #define PAYLOAD_CMD_6 55
// #define PAYLOAD_CMD_7 56
// #define PAYLOAD_CMD_8 57
// #define PAYLOAD_CMD_9 58
// #define PAYLOAD_CMD_10 59

#endif

