// CAPE-Twiggs HSSSI-26 SlimSat Project
// Copyright (c) 2025, Eric Tapio. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.


#ifndef SLIMSAT_CMD_CONSTANTS_HEADER
#define SLIMSAT_CMD_CONSTANTS_HEADER

#define MIN_SLIMSAT_CMD_ID 1
#define MAX_SLIMSAT_CMD_ID 39

// Defined SlimSat S/C Bus command values
#define PING_COMMAND_ID 1
#define REBOOT_COMMAND_ID 2
#define GET_REGISTER_COMMAND_ID 3
#define SET_REGISTER_COMMAND_ID 4
#define GET_RADIO_FREQUENCY_COMMAND_ID 5
#define SET_RADIO_FREQUENCY_COMMAND_ID 6
#define GET_RADIO_BANDWIDTH_COMMAND_ID 7
#define SET_RADIO_BANDWIDTH_COMMAND_ID 8
#define GET_RADIO_SPREAD_FACTOR_COMMAND_ID 9
#define SET_RADIO_SPREAD_FACTOR_COMMAND_ID 10
#define GET_RADIO_RSSI_COMMAND_ID 11
#define GET_BEACON_PERIOD_COMMAND_ID 12
#define SET_BEACON_PERIOD_COMMAND_ID 13
#define GET_SC_BUS_MODE_COMMAND_ID 14
#define SET_SC_BUS_MODE_COMMAND_ID 15
#define GET_SC_BUS_EPOCH_TIME_COMMAND_ID 16
#define SET_SC_BUS_EPOCH_TIME_COMMAND_ID 17
#define GET_SC_BUS_TIME_COMMAND_ID 18
#define GET_SC_BUS_DATA_COMMAND_ID 19
#define GET_DATA_STREAM_MODE_COMMAND_ID 20
#define SET_DATA_STREAM_MODE_COMMAND_ID 21
#define GET_PAYLOAD_OP_PERIOD_COMMAND_ID 22
#define SET_PAYLOAD_OP_PERIOD_COMMAND_ID 23
#define GET_PAYLOAD_MODE_COMMAND_ID 24
#define GET_PAYLOAD_DATA_COMMAND_ID 25


// Alloacated payload command values
#define PAYLOAD_CMD_1 30
#define PAYLOAD_CMD_2 31
#define PAYLOAD_CMD_3 32
#define PAYLOAD_CMD_4 33
#define PAYLOAD_CMD_5 34
#define PAYLOAD_CMD_6 35
#define PAYLOAD_CMD_7 36
#define PAYLOAD_CMD_8 37
#define PAYLOAD_CMD_9 38
#define PAYLOAD_CMD_10 39

#endif